config/routes.rb
Sosialisation::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users'
  match 'api/me' => 'api#users'
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home
  match 'api/user/:id/home' => 'api#activity_atom_feed', :format => 'atom'
  ##/API##
  
  # Webfinger
  match '.well-known/host-meta',:to => 'frontpage#host_meta'
  
  # Social Stream subjects configured in config/initializers/social_stream.rb
  SocialStream.subjects.each do |actor|
    resources actor.to_s.pluralize do
      resource :like
      resource :profile
      resources :activities
    end
  end

  resources :spheres
  namespace "relation" do
    resources :customs
  end
  resources :permissions

  match 'contacts' => 'contacts#index', :as => 'contacts'
  match 'tags'     => 'tags#index', :as => 'tags'
  
  # Find subjects by slug
  match 'subjects/lrdd/:id' => 'subjects#lrdd', :as => 'subject_lrdd'
  
  resource :representation
  
    #resources :avatars

  resources :messages
  
  resources :photos
  
  resources :musics

  resources :video_links

  resources :pdfs

  resources :docs

  resources :conversations
  
  resources :notifications

  resources :comments

  resources :ties do
    collection do
      get 'suggestion'
    end
  end
  
  resources :activities do
    resource :like
  end
  
  
  # Social Stream objects configured in config/initializers/social_stream.rb
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize
  end
end

app/helpers/toolbar_helper.rb
module ToolbarHelper
  # Define the toolbar content for your view. There are two typical cases, depending on the value of
  # options[:profile]
  # * If present, render the profile menu for the {SocialStream::Models::Subject subject}
  # * If blank, render the home menu
  #
  # The menu option allows overwriting a menu slot with the content of the given block
  #
  #
  # Autoexpanding a menu section on your view:
  #
  # Toolbar allows you to autoexpand certain menu section that may be of interest for your view.
  # For example, the messages menu when you are looking your inbox. This is done through :option element.
  #
  # To get it working, you should use the proper :option to be expanded, ":option => :messages" in the
  # mentioned example. This will try, automatically, to expand the section of the menu where its root
  # list link, the one expanding the section, has an id equal to "#messages_menu". If you use
  # ":options => :contacts" it will try to expand "#contacts_menu".
  #
  # For now its working with :option => :messages, :contacts or :groups
  #
  #
  # Examples:
  #
  # Render the home toolbar:
  #
  #   <% toolbar %>
  #
  # Render the profile toolbar for a user:
  #
  #   <% toolbar :profile => @user %>
  #
  # Render the home toolbar changing the messages menu option:
  #
  #   <% toolbar :option => :messages %>
  #
  # Render the profile toolbar for group changing the contacts menu option:
  #
  #   <% toolbar :profile => @group, :option => :contacts %>
  #

  def toolbar(options = {}, &block)
    if options[:option] && block_given?
      menu_options[options[:option]] = capture(&block)
    end

    content = capture do
      if options[:profile]
        render :partial => 'toolbar/profile', :locals => { :subject => options[:profile] }
      else
        render :partial => 'toolbar/home'
      end
    end

    case request.format
    when Mime::JS
      response = <<-EOJ

		      $('#toolbar').html("#{ escape_javascript(content) }");
		      initMenu();
		      expandSubMenu('#{ options[:option] }');
		      EOJ

      response.html_safe
    else
      content_for(:toolbar) do
        content
      end
      content_for(:javascript) do
        <<-EOJ
        expandSubMenu('#{ options[:option] }');
        EOJ
      end
    end
  end

  # Cache menu options for toolbar
  #
  # @api private
  def menu_options #:nodoc:
    @menu_options ||= {}
  end
end

app/views/toolbar/_home.html.erb
<%= render :partial => 'toolbar/logo', :locals => { :subject => current_subject, } %>

<div class="block space_center">
</div>

<%= render :partial => 'toolbar/home_menu' %>

<div class="block space_center">
</div>

app/views/toolbar/_home_menu.html.erb
<% content_for :headers do %>
  <%= stylesheet_link_tag "menu", :media => "screen, projection" %>
  <%= javascript_include_tag 'menu' %>
<% end %>

<div id="menu_lateral">
  <%= render :partial => "toolbar/home_menu_options" %>
</div>

app/views/toolbar/_home_menu_options.html.erb
<ul class="menu">

<%= menu_options[:notifications] || capture do %>
  <%= render :partial =>'toolbar/notifications_menu'%>
<% end %>

<%= menu_options[:messages] || capture do %>
  <%= render :partial =>'toolbar/message_menu'%>
<% end %>

<%= menu_options[:media] || capture do %>
  <%= render :partial =>'toolbar/media_menu'%>
<% end %>

<%= menu_options[:contacts] || capture do %>
  <li>
    <%= link_to( image_tag("btn/btn_friend.png", :class => "menu_icon")+t('contact.other'), '#', :id => "contacts_menu") %>
    <ul>
    <% current_subject.relation_customs.sort.each do |r| %>
      <li>
      <%= link_to image_tag("btn/btn_friend.png", :class => "menu_icon") + r.name , contacts_path(:relation => r.id) %>
      </li>
    <% end %>
    </ul>
  </li>
<% end %>

<%= menu_options[:subjects] || capture do %>
  <%= render :partial => 'toolbar/home_menu_options_subjects' %>
<% end %>

</ul>

app/views/toolbar/_home_menu_options_subjects.html.erb
<%= menu_options[:groups] || capture do %>
  <li>
    <%= link_to( image_tag("btn/btn_group.png", :class => "menu_icon")+t('group.other'), '#', :id => "groups_menu") %>
    <ul>
      <li>
      <%= link_to( image_tag("btn/btn_group.png", :class => "menu_icon")+t('group.new.action'), new_group_path('group' => { '_founder' => current_subject.slug })) %>
      </li>
    </ul>
  </li>

<% end %>

app/views/toolbar/_logo.html.erb
<div id="logo_index">
  <% if subject == current_subject %>
    <div class="center">
      <span class="title_bold" ><%= subject.name %></span>
      <div class="logo_grid logo_full">          
        <%= link_to image_tag(subject.logo.url, :alt => subject.name , :size => "119x119", :id => "current_avatar_img"), subject %>    
        <div class="logo_menu logo_caption">    
          <%= link_to t('avatar.profile_change'), avatars_path  %>
        </div>
      </div>        
    </div>        
  <% else %>
    <div class="center"><span class="title_bold" ><%= subject.name %></span></div>
    <%= link_to image_tag(subject.logo.url, :alt => subject.name , :size => "119x119"), subject %>
  <% end %>
</div>

app/views/toolbar/_media_menu.html.erb
<li>
  <%= link_to( image_tag("btn/btn_media.png", :class => "menu_icon")+ "Media Files", '#', :id => "media_menu") %>
  <ul>
    <li>
      <%= link_to( image_tag("btn/btn_photo.png", :class => "menu_icon")+ "Photos", photos_path) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/btn_music.gif", :class => "menu_icon")+ "Musics", musics_path) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/btn_video.gif", :class => "menu_icon")+ "Video Links", video_links_path) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/btn_pdf.jpeg", :class => "menu_icon")+ "PDF files", pdfs_path) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/btn_doc.jpeg", :class => "menu_icon")+ "Doc files", docs_path) %>
    </li>
  </ul>
</li>

app/views/toolbar/_message_menu.html.erb
<li>
  <%= link_to( image_tag("btn/new.png", :class => "menu_icon")+t('message.other'), '#', :id => "messages_menu") %>
  <ul>
    <li>
      <%= link_to( image_tag("btn/message_new.png", :class => "menu_icon")+ t('message.new'), new_message_path) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/message_inbox.png", :class => "menu_icon")+t('message.inbox')+" (" + current_subject.mailbox.inbox(:unread => true).count.to_s + ")", conversations_path, :remote => true) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/message_sentbox.png", :class => "menu_icon")+t('message.sentbox'), conversations_path(:box => :sentbox), :remote => true) %>
    </li>
    <li>
      <%= link_to( image_tag("btn/message_trash.png", :class => "menu_icon")+t('message.trash'), conversations_path(:box => :trash), :remote => true) %>
    </li>
  </ul>
</li>

app/views/toolbar/_notifications_menu.html.erb
<li>
  <%= link_to( image_tag("btn/btn_notification.png", :class => "menu_icon")+t('notification.other'), notifications_path) %>
</li>

app/views/toolbar/_profile.html.erb
<%= render :partial => 'toolbar/logo', :locals => { :subject => subject } %>

<div class="block space_center"></div>

<%= render :partial => 'toolbar/profile_menu', :locals => { :subject => subject } %>

<div class="block space_center"></div>


<%= render :partial => 'subjects/contacts', :locals => { :subject => subject } %>

<div class="block space_center"></div>
<div class="block space_center"></div>

app/views/toolbar/_profile_menu.html.erb
<% content_for :headers do %>
  <%= stylesheet_link_tag "menu", :media => "screen, projection" %>
  <%= javascript_include_tag 'menu' %>
<% end %>

<div id="menu_lateral">
  <ul class="menu">
    <% unless subject == current_subject %>
      <%= render :partial => "toolbar/profile_menu_tie_options", :locals => { :subject => subject } %>
    <% end %>

    <%= render :partial => "toolbar/profile_menu_basic_options", :locals => { :subject => subject } %>
  </ul>
</div>
<div class="space_center"></div>

app/views/toolbar/_profile_menu_basic_options.html.erb
<%= menu_options[:profile] || capture do %>
  <li>
    <%= link_to( image_tag("btn/btn_edit.png", :class => "menu_icon")+t('menu.information'), [subject, :profile]) %>
  </li>
<% end %>

app/views/toolbar/_profile_menu_tie_options.html.erb
<%= menu_options[:like] || capture do %>
  <li>
    <div class="verb_like" id="like_<%= dom_id(subject) %>">
      <%= link_like(subject)%>
    </div>
  </li>
<% end %>

<%= menu_options[:contacts] || capture do %>
  <!-- TODO: create helper -->
  <% if user_signed_in? %>
    <% if current_subject.ties_to(subject).present? %>
      <li >
      <%= link_to image_tag("btn/btn_friend.png", :class => "menu_icon")+t('tie.edit.contact', :type => current_subject.ties_to(subject).first.relation_name), edit_tie_path(current_subject.ties_to(subject).first) %>
     </li>
    <% else %>
      <li >
      <%= link_to(image_tag("btn/btn_friend.png", :class => "menu_icon")+t('tie.add.contact'), '#', :id => 'contacts_menu') %>
        <ul>
          <% current_subject.relation_customs.sort.each do |r| %>
            <li>
            <%= link_to image_tag("btn/twitter-follow-icon.png", :size => "19x19", :class => "menu_icon") + r.name,
                        ties_path('tie[sender_id]'   => current_subject.actor_id,
                                  'tie[receiver_id]' => subject.actor_id,
                                  'tie[relation_id]' => r.id),
                        :method => :post   %>
            </li>

          <% end %>
          <li>
          <%= link_to image_tag("btn/twitter-follow-icon.png", :size => "19x19", :class => "menu_icon") + t('tie.relation.new'),
                      new_tie_path('tie[sender_id]'   => current_subject.actor_id,
                                   'tie[receiver_id]' => subject.actor_id) %>
          </li>
        </ul>
      </li>
    <% end %>
  <% end %>
<% end %>

<%= menu_options[:messages] || capture do %>
  <% if user_signed_in? %>
    <li >
    <%= link_to(image_tag("btn/btn_send.png", :class => "menu_icon")+t('message.send'), new_message_path(:receiver => subject.slug)) %>
    </li>
  <% end %>
<% end %>

app/views/toolbar/_upload_progress.html.erb
      <div id="ProgressBarContainer" style="display: none;">
        <div>
          <span id="ProgressMessage"></span>
          <span id="ProgressBarText"></span>
        </div>
        <div id="ProgressBarShell">
          <div class="prog-border">
            <div id="prog-percentage" style="width: 0%;" class="prog-bar"></div>
          </div>
        </div>
      </div>
      <input type="hidden" id="X-Progress-ID" name="X-Progress-ID" value="<%= @uuid %>"/>