config/routes.rb
Sosialisation::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users'
  match 'api/me' => 'api#users'
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home
  match 'api/user/:id/home' => 'api#activity_atom_feed', :format => 'atom'
  ##/API##
  
  # Webfinger
  match '.well-known/host-meta',:to => 'frontpage#host_meta'
  
  # Social Stream subjects configured in config/initializers/social_stream.rb
  SocialStream.subjects.each do |actor|
    resources actor.to_s.pluralize do
      resource :like
      resource :profile
      resources :activities
    end
  end

  resources :spheres
  namespace "relation" do
    resources :customs
  end
  resources :permissions

  match 'contacts' => 'contacts#index', :as => 'contacts'
  match 'tags'     => 'tags#index', :as => 'tags'
  
  # Find subjects by slug
  match 'subjects/lrdd/:id' => 'subjects#lrdd', :as => 'subject_lrdd'
  
  resource :representation
  
    #resources :avatars

  resources :messages
  
  resources :photos
  
  resources :musics

  resources :video_links

  resources :pdfs

  resources :docs

  resources :conversations
  
  resources :notifications

  resources :comments

  resources :ties do
    collection do
      get 'suggestion'
    end
  end
  
  resources :activities do
    resource :like
  end
  
  
  # Social Stream objects configured in config/initializers/social_stream.rb
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_mailbox, :get_box, :get_actor
  before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]
  def index
    if @box.eql?"inbox"
      @conversations = @mailbox.inbox.paginate(:per_page => 9, :page => params[:page])
    elsif @box.eql?"sentbox"
      @conversations = @mailbox.sentbox.paginate(:per_page => 9, :page => params[:page])
    else
      @conversations = @mailbox.trash.paginate(:per_page => 9, :page => params[:page])
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end

  def new

  end

  def edit

  end

  def create

  end

  def update
    if params[:untrash].present?
    @conversation.untrash(@actor)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @actor.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read

  end

  def destroy

    @conversation.move_to_trash(@actor)

    if params[:location].present?
      case params[:location]
      when 'conversation'
        redirect_to conversations_path(:box => :trash)
        return
      else
      redirect_to conversations_path(:box => @box,:page => params[:page])
      return
      end
    end
    redirect_to conversations_path(:box => @box,:page => params[:page])
  end

  private

  def get_mailbox
    @mailbox = current_subject.mailbox
  end

  def get_actor
    @actor = Actor.normalize(current_subject)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      @box = "inbox"
    return
    end
    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

end

app/views/conversations/_conversation.html.erb
<%= div_for(conversation, :class => read_class) do %>
<div class="notification">
</div>
<div class="sender_photo">
	<%= link_to image_tag(conversation.last_sender.logo.url(:actor),
	:title => conversation.last_sender.name, :alt => conversation.last_sender.name),
	conversation.last_sender.subject %>
</div>
<div class="content_left">
	<div class="sender_name">
		<%= link_to conversation.last_sender.name, conversation.last_sender.subject %>
	</div>
	<div class="date">
		<%= t('time.ago', :time => time_ago_in_words(conversation.updated_at)) %>
	</div>
</div>
<div class="content_right">
	<div class="subject">
		<%= link_to(truncate(conversation.subject, :length => 55), conversation_path(conversation.id,:box => @box,:page => params[:page])) %>
	</div>
	<div class="briefing">
		<%= raw(truncate(strip_tags(conversation.last_message.body), :length => 50)) %>
	</div>
	<div class="clearfloat">
	</div>
</div>
<% unless @box.eql?'trash' %>
<div class="action">
	<%= link_to(image_tag('btn/btn_delete.png', :alt => "Delete", :title => "Delete"),
	conversation_path(conversation, :location => @box, :box => @box, :page => params[:page]),
	:confirm => 'Do you want to move "' + conversation.subject + '" to trash?',
	:method => :delete, :remote => true) %>
</div>
<% end %>
<div class="clearfloat">
</div>
<% end %>

app/views/conversations/_conversation_full.html.erb
<div class="title">
	<h2><%= conversation.subject %></h2>
</div>
<div class="action">
	<% unless @box.eql?'trash' %><%= link_to ( image_tag('btn/btn_delete.png', :atl => "Delete", :title => "Delete"),
	conversation_path(conversation, :location => 'conversation', :box => @box),
	:confirm => 'Do you want to move "' + conversation.subject + '" to trash?',
	:method => :delete, :remote => true) %><% end %>
</div>
<div class="clearfloat">
</div>
<div class="participants">
	<h3><%= t("message.participants") %>:</h3>
	<% conversation.recipients.each do |recp| %>
	<%= link_to image_tag(recp.logo.url(:tie), :title=>recp.name, :alt => recp.name), recp.subject %>
	<% end %>
</div>
<div class="messages">
	<% @receipts.each do |receipt| %>
	<% message = receipt.message %>
	<% read_class = message.is_unread?(@actor) ? 'unread' : '' %>
	<%= render :partial => "messages/message",:object => message, :locals => {:read_class => read_class} %>
	<% end %>

	<% unless @box.eql?'trash' %>
	<br>
	<%= form_tag conversation_path(conversation.id), :method => :put, :class => "cont_conversation" do %>
	<% if @receipt and @receipt.errors.any? %>
		<div class="error">
			<h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this message from being sent:</h2>
			<ul>
				<% @receipt.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
	<% end %>
		<div class="block">
		<div class="form_row">
			<%= t("message.answer") %>
		</div>
		<div class="form_row">
			<%= text_area_tag :body, nil,:rows =>6, :cols=> 53, :class => "required form_tag" %>
		</div>
		<div class="actions center">
			<%= submit_tag "Reply", :name => :reply_all,:class => "button" %>
		</div>
	</div>
	<% end %>
	<%end %>
</div>

app/views/conversations/_conversations.html.erb
<% @conversations.each do |conversation| %>
	<% read_class = conversation.is_unread?(@actor) ? 'unread' : '' %>
	<%= render :partial => 'conversation', :object => conversation, :locals => {:read_class => read_class} %>
<% end %>
<%= will_paginate @conversations %>

app/views/conversations/_index.html.erb
<br class="clearfloat" />
<div class="space_center">
</div>
<div class="space_center"></div>


<h2><%= t('message.' + @box) %></h2>
<div class="conversations">  
  <%= render :partial => 'conversations' %>
</div>

app/views/conversations/_menu_options.html.erb
<li>
	<%= link_to( image_tag("btn/btn_inbox.png", :class => "menu_icon")+t('message.other'), messages_path, :remote => :true) %>
</li>
<li>
	<ul>
		<li>
			<%= link_to( image_tag("btn/btn_inbox.png", :class => "menu_icon")+ t('message.new'), new_message_path) %>
		</li>
		<li>
			<%= link_to( image_tag("btn/btn_inbox.png", :class => "menu_icon")+t('message.inbox')+" (" + @mailbox.inbox(:unread => true).count.to_s + ")", messages_path, :remote => :true) %>
		</li>
		<li>
			<%= link_to( image_tag("btn/btn_inbox.png", :class => "menu_icon")+t('message.sentbox'), messages_path(:box => :sentbox), :remote => true) %>
		</li>
		<li>
			<%= link_to( image_tag("btn/btn_inbox.png", :class => "menu_icon")+t('message.trash'), messages_path(:box => :trash), :remote => true) %>
		</li>
	</ul>
</li>

app/views/conversations/_show.html.erb
<%= location(
	link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true),
	link_to(image_tag("btn/message_conversation.png", :class => "menu_icon")+ truncate(@conversation.subject, :length => 45), conversation_path(@conversation.id,:box => @box,:page => params[:page]))
) %>

<br class="clearfloat" />
<div class="space_center">
</div>
<div class="space_center">
</div>
<div class="conversation_full">  
 <%= render :partial => 'conversation_full', :locals =>{:conversation => @conversation} %>
</div>

app/views/conversations/edit.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/conversations/index.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>

<% content_for :headers do %>
  <%= stylesheet_link_tag "messages.css", :media => "screen, projection" %>
<% end %>

<% content_for :javascript do %>
  $('.pagination a').attr('data-remote', 'true');
<% end %>

<%= location(
    link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true)
) %>

<% toolbar :option => :messages %>

<%= render :partial => 'index' %>

app/views/conversations/index.js.erb
$("#content").html("<%=escape_javascript(render :partial => 'index') %>");
<%= location(link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true)) %>

$('.pagination a').attr('data-remote', 'true');
	  

$("head").append($("<%= escape_javascript(stylesheet_link_tag "messages.css", :media => "screen, projection") %>"));

<%= toolbar :option => :messages %>

app/views/conversations/show.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>

<% toolbar :option => :messages %>

<% content_for :headers do %>
<%= stylesheet_link_tag "messages.css", :media => "screen, projection" %>
<%= javascript_include_tag 'ckeditor/ckeditor.js','ckeditor/adapters/jquery.js','jquery.scrollTo.min.js', 'jquery.validate' %>
<% end %>

<% content_for :javascript do %>
$('.cont_conversation').validate();
<% unless @box.eql?'trash' %>
$('#body').ckeditor(
	function(){
		$('#cke_top_body').click(updateTextArea);
		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash.length > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
		}}
	,{ width:525 }
);
var editor = $('#body').ckeditorGet();
editor.on("instanceReady", function(){
this.document.on("keyup", updateTextArea);
this.document.on("paste", updateTextArea);
this.document.on("mousedown", updateTextArea);
});

var updateTextArea = function (){
editor.updateElement();
$("#body").trigger('keyup');
}
<% else %>
		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});	
		}
<% end %>
<% end %>

<%= render :partial => 'show' %>

app/views/conversations/show.js.erb
$("#content").html("<%= escape_javascript(render :partial => 'show') %>");

$("head").append($("<%= escape_javascript(stylesheet_link_tag "messages.css", :media => "screen, projection")  %>"));

$("head").append($("<%= escape_javascript(javascript_include_tag 'ckeditor/ckeditor.js','ckeditor/adapters/jquery.js','jquery.scrollTo.min.js', 'jquery.validate')  %>"));

<%= toolbar :option => :messages %>

$('.cont_conversation').validate();
<% unless @box.eql?'trash' %>
	$('#body').ckeditor(
		function(){$('#cke_top_body').click( updateTextArea);
		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash.length > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
		}
		},
		{ width:525, customConfig:'/javascripts/ckeditor/config.js',skin:'../javascripts/ckeditor/skins/kama'}
	);
	var editor = $('#body').ckeditorGet();
		editor.on("instanceReady", function(){
			this.document.on("keyup", updateTextArea);
			this.document.on("paste", updateTextArea);
			this.document.on("mousedown", updateTextArea);
		}
	);
	
	var updateTextArea = function (){
		editor.updateElement();
		$("#body").trigger('keyup');
	}
<% else %>
	var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash.length > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
		}
<% end %>