config/routes.rb
Sosialisation::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  root :to => "frontpage#index"
  
  match 'home' => 'home#index', :as => :home
  match 'home' => 'home#index', :as => :user_root # devise after_sign_in_path_for
  
  ##API###
  match 'api/keygen' => 'api#create_key', :as => :api_keygen
  match 'api/user/:id' => 'api#users'
  match 'api/me' => 'api#users'
  match 'api/me/home/' => 'api#activity_atom_feed', :format => 'atom', :as => :api_my_home
  match 'api/user/:id/home' => 'api#activity_atom_feed', :format => 'atom'
  ##/API##
  
  # Webfinger
  match '.well-known/host-meta',:to => 'frontpage#host_meta'
  
  # Social Stream subjects configured in config/initializers/social_stream.rb
  SocialStream.subjects.each do |actor|
    resources actor.to_s.pluralize do
      resource :like
      resource :profile
      resources :activities
    end
  end

  resources :spheres
  namespace "relation" do
    resources :customs
  end
  resources :permissions

  match 'contacts' => 'contacts#index', :as => 'contacts'
  match 'tags'     => 'tags#index', :as => 'tags'
  
  # Find subjects by slug
  match 'subjects/lrdd/:id' => 'subjects#lrdd', :as => 'subject_lrdd'
  
  resource :representation
  
    #resources :avatars

  resources :messages
  
  resources :photos
  
  resources :musics

  resources :video_links

  resources :pdfs

  resources :docs

  resources :conversations
  
  resources :notifications

  resources :comments

  resources :ties do
    collection do
      get 'suggestion'
    end
  end
  
  resources :activities do
    resource :like
  end
  
  
  # Social Stream objects configured in config/initializers/social_stream.rb
  (SocialStream.objects - [ :actor ]).each do |object|
    resources object.to_s.pluralize
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
  has_attached_file :music
  validates_attachment_presence :music
  validates_attachment_content_type :music, :content_type => ['audio/mid', 'audio/mpeg', 'audio/x-wav', 'audio/wav', 'video/mpeg', 'video/x-flv', 'video/mp4', 'video/mov', 'video/f4v'],
                                    :message => 'file is not be supported'

  validates_attachment_size :music, :less_than => 50.megabytes
  validates :title, :description, :presence => true
end

app/controllers/musics_controller.rb
class MusicsController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :generate_progress_key, :only => [:new, :edit, :create, :update]

  def index
    page = params[:page] || 1
    @musics = Music.paginate(:page => page, :per_page => 20)
  end

  private

  def generate_progress_key
    @uuid = (0..29).to_a.map {|x| rand(10)}.join("")
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<% content_for :headers do %>
  <%= stylesheet_link_tag "progress" %>
  <%= javascript_include_tag "upload" %>
<% end %>
<%= form_for(@music, :class => "new_message", :html => {:id => :submit_form,  :multipart => true}) do |f| %>
  <% if @music.errors.any? %>
  <div class="error">
    <h2><%= pluralize(@music.errors.count, "error") %> prohibited this message from being sent:</h2>
      <ul>
        <% @music.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
  <div class="block">
    <div class="form_row">
      <%= label_tag :title %>
    </div>
    <div class="form_row">
      <%= f.text_field :title, :class => "required form_tag" %>
    </div>
    <div class="form_row">
      <%= label_tag :description %>
    </div>
    <div class="form_row" id="ck_editor" >
      <%= f.text_area :description, {:rows =>6, :cols=> 53, :class => "required form_tag", :maxlength => 5000} %>
    </div>
    <div class="form_row">
      <%= label_tag "Choose music file" %>
    </div>
    <div class="form_row">
      <%= f.file_field :music, :class => "required form_tag" %>
    </div>
    <input type="hidden" value="1" name="music[_activity_tie_id]"/>
    <div class="actions center">
      <%= render :partial => "/toolbar/upload_progress" %>
      <%= submit_tag "Upload", :id => "submit", :class => "button" %>
    </div>
  </div>

<% end %>

app/views/musics/edit.html.erb
<% toolbar :option => :media %>
<% content_for :title do%>
  <%= current_subject.name %>
<% end%>
<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>

<%= location(
  link_to(image_tag("btn/btn_music.gif", :class => "menu_icon")+ "Musics", musics_path)
) %>

<br class="clearfloat" />

<div id="conversation">
  <h2>Editing Music</h2>
  <%= render 'form' %>
  <div style="float:right; padding-right: 30px;">
    <%= link_to 'Show', @music %> |
    <%= link_to 'All Musics', musics_path %>
  </div>
</div>

app/views/musics/index.html.erb
<% toolbar :option => :media %>
<% content_for :title do%>
  <%= current_subject.name %>
<% end%>
<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>

<%= location(
  link_to(image_tag("btn/btn_music.gif", :class => "menu_icon")+ "Musics", musics_path)
) %>

<br class="clearfloat" />
<div id="conversation">
  <h2>All Musics</h2>
  <div>
    <% if @musics.total_pages > 1 %>
    <div style="margin: 10px; padding: 10px; border-top: thin solid #D4E4EA;">
      <div style="float:right"><%= will_paginate @musics %></div>
    </div>
    <% end %>
    <% @musics.each_with_index do |music, i| %>
      <div style="margin: 10px; padding: 10px; border-top: thin solid #D4E4EA;">
        <div class="form_row">
          <label>Title:</label><b> <%= music.title %></b>
        </div>
        <div class="form_row">
          <label>Description:</label> <%= music.description %>
        </div>
        <div class="form_row">
          <label>Updated at:</label> <%= music.music_updated_at %>
        </div>
        <div style="float:right;">
          <%= link_to 'Download', music.music.url %> |
          <%= link_to 'Show', music %> |
          <%= link_to 'Edit', edit_music_path(music) %> |
          <%= link_to 'Destroy', music, :confirm => 'Are you sure?', :method => :delete %>
        </div>
      </div>
    <% end %>
    <% if @musics.total_pages > 1 %>
    <div style="margin: 10px; padding: 10px; border-top: thin solid #D4E4EA;">
      <div style="float:right"><%= will_paginate @musics %></div>
    </div>
    <% end %>
    <div style="margin: 10px; padding: 10px; border-top: thin solid #D4E4EA;">
      <%= link_to 'Add New Music', new_music_path, :style => "float: right;"%>
    </div>
  </div>
 
</div>

app/views/musics/new.html.erb
<% toolbar :option => :media %>
<% content_for :title do%>
  <%= current_subject.name %>
<% end%>
<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>

<%= location(
  link_to(image_tag("btn/btn_music.gif", :class => "menu_icon")+ "Musics", musics_path)
) %>

<br class="clearfloat" />

<div id="conversation">
  <h2>New Music</h2>
  <%= render 'form' %>
  <div style="float:right; padding-right: 30px;">
    <%= link_to 'All Musics', musics_path %>
  </div>
</div>

app/views/musics/show.html.erb
<% toolbar :option => :media %>
<% content_for :title do%>
  <%= current_subject.name %>
<% end%>
<% content_for :sidebar do %>
  <%= render :partial => 'home/sidebar' %>
<% end %>
<% content_for :headers do %>
  <%= javascript_include_tag 'jwplayer.js' %>
<% end %>

<%= location(
  link_to(image_tag("btn/btn_music.gif", :class => "menu_icon")+ "Musics", musics_path)
) %>

<br class="clearfloat" />

<div id="conversation">
  <h2>Music details</h2>
  <!-- START OF THE PLAYER EMBEDDING TO COPY-PASTE -->
  <div style="padding:30px;">
    <div class="form_row">
      <label>Title:</label> <b><%= @music.title %></b>
    </div>
    <div class="form_row">
      <label>Updated at:</label> <%= @music.music_updated_at %>
    </div>
    <div class="form_row" style ="padding-top: 15px; padding-bottom: 15px;">
      <div id="mediaplayer">JW Player goes here</div>
    </div>
    <div class="form_row">
      <%= @music.description %>
    </div>
  </div>

  <script type="text/javascript">
    jwplayer("mediaplayer").setup({
      flashplayer: "../swf/player.swf",
      file: "<%= @music.music.url %>",
      height: 350,
      width: 500
    });
  </script>
  <!-- END OF THE PLAYER EMBEDDING -->
  <div style="float:right; padding-right: 30px;">
    <%= link_to 'Download', @music.music.url %> |
    <%= link_to 'Edit', edit_music_path(@music) %> |
    <%= link_to 'All Musics', musics_path %>
  </div>
</div>